$(document).ready(function(){
	$('.header-burger').click(function(event){
		$('.header-burger,.header-menu,.header').toggleClass('activeg');
		$('body').toggleClass('lock');
	});
});
$(document).ready(function(){
  $('.g').click(function(event){
    $('.header-burger,.header-menu,.header').removeClass('activeg');
    $('body').removeClass('lock');
  });
});